class Config:
    # --- Training Setup ---
    NUM_EPISODES = 1000
    TRAIN_SEEDS = [42, 100, 2024]
    EVAL_SEEDS_PER_TRAIN_SEED = 200
    
    # --- DQN Parameters ---
    LR = 3e-4
    GAMMA = 0.99
    BUFFER_CAPACITY = 100000
    BATCH_SIZE = 64
    TAU = 0.005
    USE_ENHANCED_DQN = True
    PER_ALPHA = 0.6
    PER_BETA_START = 0.4
    PER_BETA_FRAMES = 50000
    N_STEP = 3
    REWARD_CLIP = 10.0
    GRAD_CLIP_NORM = 10.0
    
    # --- Epsilon-Greedy ---
    EPSILON_START = 1.0
    EPSILON_MIN = 0.05
    EPSILON_DECAY = 0.99
    
    # --- Environment & Robustness ---
    LIDAR_NOISE_STD = 0.0
    DYNAMIC_OBS_SPEED_MULTIPLIER = 1.0
    EVAL_START_POS_NOISE = 0.08
    EVAL_START_THETA_NOISE = 0.20
    EVAL_RANDOM_START = True
    EVAL_START_REGION_RADIUS = 2.0
    DYNAMIC_OBS_PHASE_JITTER_STEPS = 25
    STATIC_OBSTACLE_DENSITY = 0.0
    TRAIN_EVAL_START_PROB = 0.35
    TRAIN_DYN_OBS_PHASE_JITTER_STEPS = 25
    USE_TRAIN_CURRICULUM = True
    TRAIN_CURRICULUM_WARMUP_FRAC = 0.20
    TRAIN_CURRICULUM_RAMP_FRAC = 0.45
    
    # --- Robustness Sweeps ---
    ROBUSTNESS_LIDAR_NOISE = [0.0, 0.03, 0.06, 0.10]
    ROBUSTNESS_DYN_SPEED = [0.75, 1.0, 1.25, 1.5]
    ROBUSTNESS_STATIC_DENSITY = [0.0, 0.005, 0.01]
